// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderManagerCLI.Contexts;

namespace OrderManagerCLI.Migrations
{
    [DbContext(typeof(ECommerce2Context))]
    partial class ECommerce2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("OrderManagerCLI.ContextModels.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "b4b5a9c9-70c5-4e91-b0c6-e38c94475659",
                            Price = 10m,
                            ProductName = "Ürün 1",
                            Quantity = 100
                        },
                        new
                        {
                            ProductId = "f5ed9460-f063-4b0d-92fb-d0e605c65457",
                            Price = 10m,
                            ProductName = "Ürün 2",
                            Quantity = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
